### ISSUE TITLE
Visibilità dell'immagine di anteprima del template

### ISSUE THREAD

**Issue by Knock-Out** [pcrt/joomla-italia-theme#1]
### **Steps to reproduce the issue**

- Dashboard di sistema
- Template
- Template del sito

### **Expected result**

La visibilità dell'immagine di anteprima del template si riferisce alla capacità di visualizzare l'immagine di anteprima del modello in modo chiaro e completo.

### **Actual result**

L'immagine di anteprima mancante.

![Template  Template  Sito  - Joomla Italia Theme - Amministrazione](https://github.com/pcrt/joomla-italia-theme/assets/24791536/f81bf5eb-21f6-45d9-80f1-94236f4ca0d4)

**Comment by pcrt** [comment]
risolto Sarà disponibile dalla release 1.2
