### ISSUE TITLE
Formattazione Data e Descrizione in dettaglio eventi non corretta

### ISSUE THREAD

**Issue by danilomariotti** [pcrt/joomla-italia-theme#16]
Nella visualizzazione del dettaglio dell'evento non riesco ad ottenere la formattazione del sito demo. Ho controllato più volte la documentazione ma non riesco a capire se dove sto sbagliando.
Ottengo questo:
![2023_06_09_16_18_50_Evento_1](https://github.com/pcrt/joomla-italia-theme/assets/47560555/de016f6d-5aa7-4afa-9c5f-5a592725f6f9)
invece di questo:
![2023_06_09_16_19_46_Chiusura_scolastica](https://github.com/pcrt/joomla-italia-theme/assets/47560555/38b8f5dc-12d7-48eb-b843-96b34c4f4179)

**Comment by pcrt** [comment]
Nel campo personalizzato "Riga Data Tempi e scadenze" di tipo sottomodulo devi selezionare il layout calendario-evento. Nel campo personalizzato "Riga Descrizione data tempi e scadenze" devi selezionare il layout "calendario-descrizione"

**Comment by danilomariotti** [comment]
Infatti stavo proprio cercando il layout adatto.
Le voci che mi hai indicato però non esistono:

![2023_06_09_16_53_59_Articoli_Modifica_campo_aggiuntivo_I I S _G _Spagna_F lli_Campani_Ammin](https://github.com/pcrt/joomla-italia-theme/assets/47560555/e363fe4c-d424-4496-b70d-7531bf612f9b)
![2023_06_09_16_54_45_Articoli_Modifica_campo_aggiuntivo_I I S _G _Spagna_F lli_Campani_Ammin](https://github.com/pcrt/joomla-italia-theme/assets/47560555/05cb89c5-1852-465b-890a-4d41a58d026d)

**Comment by pcrt** [comment]
ho scritto male mi correggo: calendario-data e calendario-descrizione

**Comment by danilomariotti** [comment]
Sono esattamente i layout che sto già utilizzando, con quel risultato

**Comment by danilomariotti** [comment]
Qualche suggerimento?

**Comment by pcrt** [comment]
controlla di aver assegnato il giusto layout ad ogni custom field

**Comment by pcrt** [comment]
Se hai settato i layout nella maniera corretta l'unica cosa che mi viene in mente è che forse devi nominare i  campi esattamente come nella demo, purtroppo i custom field di tipo subform non sono overridabili in Joomla ed in alcuni casi ho dovuto agire con il nome del campo

**Comment by Knock-Out** [comment]
Credo che questo sia il tuo problema.

Campo Date e Orari

![Articoli  Modifica campo aggiuntivo - Joomla Italia Theme - Amministrazione](https://github.com/pcrt/joomla-italia-theme/assets/24791536/189533e6-e5ce-47d8-a8b8-6a1dea1addc0)

Layout  >> h4titolosubform

**Comment by danilomariotti** [comment]
Hai voglia a fare "esattamente" come scritto nella documentazione! :))
@pcrt Grazie della dritta!!

**Comment by pcrt** [comment]
se cortesemente puoi aprire una issue così da poterla sistemare.
Grazie
