### ISSUE TITLE
Fumetto segnaposto posizione mappa vuoto

### ISSUE THREAD

**Issue by danilomariotti** [pcrt/joomla-italia-theme#19]
Steps to reproduce the issue

- Caricare un luogo e fornire le coordinate GPS
- Visualizzare il luogo

Expected result
La mappa dovrebbe mostrare il fumetto sopra il segnaposto con li nome del luogo

Actual result
Il fumetto è vuoto

![2023_06_10_18_46_42_Plesso_ITCG_G _Spagna_](https://github.com/pcrt/joomla-italia-theme/assets/47560555/89f6c748-060f-4eb4-b77f-1cc5855dc0e0)

**Comment by pcrt** [comment]
non riesco a replicare l'errore. Prova a ricontrollare bene la documentazione ed i custom field

**Comment by danilomariotti** [comment]
Non riesco a trovare errori nella definizione dei custom field. Se mi dai qualche indicazione su come viene popolato il popup della mappa posso indagare meglio

**Comment by pcrt** [comment]
il custom field di tipo subform dovrebbe avere esattamente uno di questi tre nomi (Case sensitive), potrebbe essere questa la soluzione:

- Luoghi in cui viene erogato il servizio
- Dove si trova
- Sede
- Luogo

**Comment by pcrt** [comment]
Il custom field che contiene il nome della sede dovrebbe avere esattamente questo titolo (Case Sensitive)
Nome Sede 
NOME SEDE

**Comment by danilomariotti** [comment]
Era proprio il nome con la "s" minuscola! :) Però sono stato tratto in inganno dalla documentazione:
![2023_06_13_11_46_34_joomla_italia_theme_doc_custom_field_articoli md_at_main_pcrt_joomla_italia_th](https://github.com/pcrt/joomla-italia-theme/assets/47560555/cd60db28-d89c-46bd-96b8-599689bf822b)

Una domanda: ma quando si hanno campi duplicati in più subform di categorie diverse, vanno ricreati per ogni categoria (come in questo caso sia in luoghi che eventi) oppure possono essere riutilizzati tra categorie diverse? Nella documentazione vengono specificati una sola volta in una delle categorie.

**Comment by pcrt** [comment]
possono essere riutilizzati gli stessi.
