### ISSUE TITLE
Language - TPL_PCRT_COPYRIGHT_DESCRIPTION

### ISSUE THREAD

**Issue by Knock-Out** [pcrt/joomla-italia-theme#2]
### **Steps to reproduce the issue**

- Dashboard di sistema
- Stili Template Sito
- joomla-italia-theme
- Tab Copyright

### **Expected result**

La visibilità della descrizione del copyright si riferisce alla capacità di visualizzare chiaramente e facilmente la descrizione del tab.

### **Actual result**

Descrizione mancante nel file tpl_joomla-italia-theme.ini

![Template  Modifica stile - Joomla Italia Theme - Amministrazione](https://github.com/pcrt/joomla-italia-theme/assets/24791536/aaf8b1c1-6ccd-44e9-8233-d4d13bdf40bc)

**Comment by joomlaphp** [comment]
Sorry for posting here. @Knock-Out 
I didn't want to open a new Issues. Tabs and their contents are also missing languages.

![sekme](https://github.com/pcrt/joomla-italia-theme/assets/423588/ce7a8402-b612-498f-8772-6a10149b4d14)
