### ISSUE TITLE
I font non vengono caricati

### ISSUE THREAD

**Issue by mariantanase** [pcrt/joomla-italia-theme#21]
Dopo la modifica (spostamento) degli assets nella cartella media, bisogna cambiare anche i relativi percorsi nel `fonts.css`.
Es.:
Sostituire:
`url('/media/templates/site/joomla-italia-theme/fonts/Lora/lora-v20-latin-ext_latin-italic.eot');`
con
`url('../fonts/Lora/lora-v20-latin-ext_latin-italic.eot');`

**Comment by pcrt** [comment]
prova a scaricare la release 1.2 ed installarla dal pannello di joomla. Così facendo i font verranno aggiunti alla cartella media

**Comment by mariantanase** [comment]
Sono d'accordo che sono aggiunti, ma i percorsi rimangono i stessi, quindi vanno modificati.

**Comment by pcrt** [comment]
in realtà lo spostamento su media è parziale il template legge js e css dalla cartella del template mentre i font e il css per la modale sono su media. Quindi quelle cartelle servono. Chiaro che con una installazione da zero tutto risulterà più pulito perchè non verranno portate dentro risorse inutili.

**Comment by pcrt** [comment]
Ho provato un'installazione pulita di Joomla in questo caso il sito utilizza le risorse presenti nella cartella media. Mentre per installazioni precedenti alla 1.1 utilizza le risorse presenti nella cartella template.

**Comment by danilomariotti** [comment]
Disinstallata v1.1 e installata la 1.2.
Nessun font viene caricato dovuto al fatto che, avendo una installazione in una sottocartella ed avendo il file fonts.css dei percorsi che iniziano con '/media/templates....." i percorsi sono errati.
Visto che questo problema dei percorsi errati quando si usa una sottocartella si ripropone molto spesso ed in varie situazioni (ved. icone, link, ecc.) , credo che andrebbe programmata una revisione completa del template proprio per prevederne l'uso corretto in una sottocartella.
