### ISSUE TITLE
Percorsidi studi trattati come servizi

### ISSUE THREAD

**Issue by danilomariotti** [pcrt/joomla-italia-theme#23]
Steps to reproduce the issue

Caricare i corsi di studi utilizzando la categoria "Percorsi di studio"

Expected result
- I percorsi di studio dovrebbero avere una sola sezione "Cos'è" invece di tutte le sezioni previste per i Servizi che rappresentano informazioni inutili e spesso non disponibili
- Il campo Cos'è deve essere di tipo "editor"
- I percorsi di studio non dovrebbero essere elencati nell'elenco dei servizi in home. Oltre che non essere corretto, in caso di numerosi Percorsi di studio, si va a sovrastare l'elenco degli effettivi servizi offerti 
- (ved. modello Wprdpress)

Actual result

- Per caricare i Percorsi di studio occorre caricare tutte le sezioni previste nei servizi
- Il campo Cos'è è di tipo textarea
- Nell'elenco sei Servizi in home appaiono anche i Percorsi di studio

![2023_06_12_15_35_31_Manutenzione_e_Assistenza_Tecnica](https://github.com/pcrt/joomla-italia-theme/assets/47560555/1dd50bcb-97da-4233-b20d-d33d5ca1f39a)

![2023_06_12_15_34_19_Home](https://github.com/pcrt/joomla-italia-theme/assets/47560555/d5cb3869-9c55-4d17-8331-c8effeaa049e)

---edit

Valutando meglio, credo che alcuni dei campi dei servizi potrebbero essere utili a fornire ulteriori informazioni, magari rendendoli non obbligatori. Resta comunque importante non elencarli in home insieme ai servizi veri e propri

**Comment by pcrt** [comment]
Esatto puoi configurare i custom field come non obbligatori. Tuttavia così facendo il sito perderà punteggio nell'app di valutazione scuole

**Comment by danilomariotti** [comment]
Resta però il fatto che andrebbero tolti i Percorsi di studio dall'elencazione a fine pagian nella home, come d'altronde accade nel modello Wordpress. Oltretutto li troviamo subito sotto in blu bene evidenti.
![2023_06_13_11_33_47_Home](https://github.com/pcrt/joomla-italia-theme/assets/47560555/912e6a5d-02f9-4bf5-9b0e-efa2ccfa8cb6)

Con l'occasione: ma c'è un modo per stabilirne l'ordine di visualizzazione?
