### ISSUE TITLE
Colore e formattazione scheda Novità

### ISSUE THREAD

**Issue by danilomariotti** [pcrt/joomla-italia-theme#26]
Steps to reproduce the issue

    Scegliere dal menu principale Novità -> Panoramica
    
Expected result

- Utilizzo del tema verde 
- Formattazione Eventi corretta

Actual result

- Viene utilizato il tema fucsia
- Nella formattazione degli eventi la mappa esce dal box
- Da notare, inoltre che il testo in alto a sinistra vicino al Logo viene mal riprodotto, non entra in altezza, quando il nome e la descrizione della scuola sono un po' lunghi
![Screenshot 2023-06-13 at 18-34-03 Novità](https://github.com/pcrt/joomla-italia-theme/assets/47560555/c07584ee-2524-4202-8727-e9f42cebb873)

**Comment by fabiojust** [comment]
Temo che tu abbia associato il layout "servizi" alla categoria "novità".
Controlla di aver eseguito correttamente questa procedura: 

## 1.7. Novità

Creare una nuova voce di menu denominata “novità” di tipo “categoria blog”. Su scegli una categoria seleziona “novità” Nella tab opzioni -> scegli un layout -> novita Categoria -> nascondi.

**Comment by danilomariotti** [comment]
> Temo che tu abbia associato il layout "servizi" alla categoria "novità". Controlla di aver eseguito correttamente questa procedura:
> ## 1.7. Novità
> 
> Creare una nuova voce di menu denominata “novità” di tipo “categoria blog”. Su scegli una categoria seleziona “novità” Nella tab opzioni -> scegli un layout -> novita Categoria -> nascondi.

Controllato, è già così:

![2023_06_29_00_29_21_Menu_Modifica_voce_di_menu_I I S _G _Spagna_F lli_Campani_Amministrazio](https://github.com/pcrt/joomla-italia-theme/assets/47560555/66a19805-d5d7-4b8f-bc03-6d8c5f3ace29)

**Comment by danilomariotti** [comment]
> ## 1.7. Novità
> 
> Creare una nuova voce di menu denominata “novità” di tipo “categoria blog”. Su scegli una categoria seleziona “novità” Nella tab opzioni -> scegli un layout -> novita Categoria -> nascondi.

E' sbagliata la documentazione, non deve essere "categoria blog" ma "Blog per le categorie della sezione Novità". Corretto e ora è verde!
