### ISSUE TITLE
La voce di menu "A cosa serve" non appare

### ISSUE THREAD

**Issue by danilomariotti** [pcrt/joomla-italia-theme#30]
Steps to reproduce the issue

-  Caricare un servizio e definire anche il campo "A cosa serve"
-  Visualizzare il servizio

Expected result

- Nel menu a sinistra dovrebbe apparire anche la voce "A cosa serve"

Actual result

- La voce "A cosa serve" non appare

**Comment by pcrt** [comment]
Il campo a Cosa serve non deve essere obbligatoriamente presente nell'indice come descritto nella documentazione scuole punto 6.1.1
https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-scuole.html
