### ISSUE TITLE
Disponibilità Quickstart - dump DB sito Demo

### ISSUE THREAD

**Issue by danilomariotti** [pcrt/joomla-italia-theme#34]
Nel confermare l'ottimo lavoro che avete svolto fin qui nello sviluppo del template Scuole vorrei riportare l'attenzione su ciò che qualche tempo fa si discuteva nel Forum Italia e cioè della predisposizione di una Quickstart.
Ho investito diverso tempo nella configurazione e sperimentazione del template e credo che il mio sito di test abbia raggiunto un livello molto più che soddisfacente, sia a livello tecnico che "estetico".
Ho anche notato che buona parte degli inconvenienti strutturali da me riscontrati erano dovuti ad una male interpretazione della guida da parte mia ma anche da errori e/o omissioni nella guida stessa e ne restano ancora di irrisolti.
Viste le scadenze imminenti, mi trovo nella necessità di iniziare a popolare seriamente il sito ma prima vorrei trovarmi in una situazione sufficientemente stabile, per evitare che eventuali interventi sulla struttura possano causarmi perdite di dati e costringermi a ripetere parte del lavoro. Non ultima la necessità di essere conformi e superare il test di validità del'App!

Quindi vi chiederei gentilmente la possibilità di avere il Dump del database del vostro sito demo del liceo Battaglia che io tengo sempre come riferimento funzionale e che per me può rappresentare quella situazione di partenza "stabile" di cui parlavo e la possibilità di studiare a fondo come sia stato poi utilizzato concretamente il template. 
La Quickstart sicuramente non sarà disponibile compatibilmente con i tempi di cui dispongo quindi per me sarebbe veramente importante iniziare subito il lavoro.

Vi ringrazio anticipatamente.

Danilo

**Comment by pcrt** [comment]
abbiamo in programma la realizzazione di un quickstart, ma prima dell'autunno

**Comment by danilomariotti** [comment]
Beh, immagino sia un lavoro molto complesso... nel frattempo basterebbe avere anche solo le tabelle:

_categories
_fields
_fields_categories
_fields_groups
_menu

che sono interessate fin'ora dalla maggior parte delle male interpretazioni, imprecisioni e omissioni della guida.

**Comment by micheste** [comment]
Buongiorno. Vi è stata poi una predisposizione di una Quickstart?
Grazie 
Michelangelo

**Comment by vittorioalfieri** [comment]
Rinnovo la possibilità di avere una copia delle tabelle con i campi custom e dei menu, anche io sto trovando una certa difficoltà nel "rispettare" la guida.

Grazie 1000 e ancora complimenti per il lavoro svolto fino a qua!
