### ISSUE TITLE
Campo aggiuntivo "descrizione notizia"

### ISSUE THREAD

**Issue by fabiojust** [pcrt/joomla-italia-theme#35]
Problemi:

- Il campo aggiuntivo "descrizione notizia" è di tipo "textarea" ma questo non consente di inserire altro che testo all'interno della notizia (no link, no a capo, no video)
- Il testo è in carattere Tititllium
- è visibile il titolo "descrizione notizia"

![Screenshot_20230628_231545](https://github.com/pcrt/joomla-italia-theme/assets/121680339/93698a03-202e-44d9-b694-ca82164a3bb7)

**Comment by danilomariotti** [comment]
> Problemi:
> 
>     * Il campo aggiuntivo "descrizione notizia" è di tipo "textarea" ma questo non consente di inserire altro che testo all'interno della notizia (no link, no a capo, no video)
> 
>     * Il testo è in carattere Tititllium
> 
>     * è visibile il titolo "descrizione notizia"
> 
> 
> ![Screenshot_20230628_231545](https://user-images.githubusercontent.com/121680339/249617507-93698a03-202e-44d9-b694-ca82164a3bb7.png)

Io infatti l'ho definita "editor", avrebbe poco senso "textarea".

**Comment by fabiojust** [comment]
Già. Però qui vorrei capire qual è l'errore perchè, da ignorante, io avrei agganciato il campo default dell'articolo alla parte sotto (in modo da poter utilizzare tutto il database delle notizie già scritte, senza doverle sistemare una a una) e la descrizione in alto a sinistra sotto il titolo.

**Comment by danilomariotti** [comment]
Se parli degli articoli storici presenti nel tuo sito credo che il contenuto originario dell'articolo non possa che rimanere nella parte sotto al titolo che proviene dal campo standard Joomla "Testo articolo" della tab "Contenuto" (tra l'altro viene pure "sformattato" in quanto considerato un sottotitolo, credo). Il campo descrizione è un campo aggiuntivo che prima dell'adozione del template non esisteva proprio e quindi credo che dovrai popolarlo con un bel copia+incolla ;)
Però sentiamo cosa ci dicono, magari c'è un'altra soluzione...

**Comment by fabiojust** [comment]
Basterebbe invertire i campi "contenuto" e "descrizione notizia", in questo modo:
- lo storico notizie sarebbe riutilizzabile
- nell'articolo sarebbero inseribili link e altro
Attendiamo gli sviluppatori

**Comment by pcrt** [comment]
> Basterebbe invertire i campi "contenuto" e "descrizione notizia", in questo modo:
> 
> * lo storico notizie sarebbe riutilizzabile
> * nell'articolo sarebbero inseribili link e altro
>   Attendiamo gli sviluppatori

tecnicamente è fattibile ma per poter mantenere la compatibilità del template con chi ha utilizzato il metodo attuale non possiamo intervenire in questo senso mi dispiace

**Comment by pcrt** [comment]
> Ritengo che l'editor principale dell'articolo possa essere utilizzato in parte come introduzione della descrizione estesa della notizia. Tuttavia, ho riscontrato che il testo non mantiene la formattazione assegnata tramite l'editor, anche se questo potrebbe essere voluto e impostato nel layout. Inoltre, confermo che la descrizione della notizia dovrebbe essere di tipo editor e non di tipo text area.

credo che questo sia un piccolo bug del template. Puoi aprire una issue specifica grazie
