### ISSUE TITLE
Allegare documenti pdf negli articoli 

### ISSUE THREAD

**Issue by stefanobonato** [pcrt/joomla-italia-theme#36]
Sto configurando e sperimentando il template sul sito della mia scuola [www.liceoariosto.edu.it](https://liceoariosto.edu.it/Joomla4/) e a parte alcuni inconvenienti dovuti a una erronea interpretazione della documentazione da parte mia, non riesco a riprodurre l’inserimento di documenti in formato pdf così come appaiono nella pagina “I filosofi della Stoa” del [Sito dimostrativo di esempio](https://jit.protocollicreativi.it/) vi chiederei pertanto di avere indicazioni in merito
Vi ringrazio anticipatamente per l’eventuale soccorso
Stefano

**Comment by danilomariotti** [comment]
Però quelle de sito demo sembrano essere delle vere e proprie "card".  Credo che l'attuale versione del template non corrisponda esattamente a quella del sito demo.

**Comment by fabiojust** [comment]
Sì, chiedo scusa, non avevo individuato che si trattava di una scheda didattica

**Comment by stefanobonato** [comment]
Grazie a tutti per le informazioni. 
Sono riuscito a riprodurre la card come nel sito demo, basta nella tab Opzioni del campo Documenti di tipo editor sostituire Layout: usa predefinito con Layout: documento, ma ora il problema è un altro. Quando in un campo editor inserisco una qualsiasi formattazione (link, elenco puntato, ...) e salvo, nel frontend il testo è senza formattazione. Riapro l'editor e vedo che la formattazione è sparita…
Sto lavorando in locale usando XAMPP for Linux 8.1.12-0

**Comment by pcrt** [comment]
> Grazie a tutti per le informazioni. Sono riuscito a riprodurre la card come nel sito demo, basta nella tab Opzioni del campo Documenti di tipo editor sostituire Layout: usa predefinito con Layout: documento, ma ora il problema è un altro. Quando in un campo editor inserisco una qualsiasi formattazione (link, elenco puntato, ...) e salvo, nel frontend il testo è senza formattazione. Riapro l'editor e vedo che la formattazione è sparita… Sto lavorando in locale usando XAMPP for Linux 8.1.12-0

Ciao scusa, potresti indincarmi in quali pagine e in quali campi l'editor perde la formattazione? Così che possa controllare grazie
