### ISSUE TITLE
L'aggiunta di allegati successivo al primo provoca l'inserimento del link nell'editor del primo allegato

### ISSUE THREAD

**Issue by danilomariotti** [pcrt/joomla-italia-theme#39]
Steps to reproduce the issue

- Aggiungere un allegato ad una scheda didattica e scegliere un file usando il media manager
- Aggiunger un secondo allegato, portare il cursore all'interno dell'editor del secondo allegato e scegliere una altro file usando il media manager

Expected result

- Il link del primo file appare all'interno dell'editor del primo allegato
- Il link del secondo file appare all'interno dell'editor del secondo allegato

Actual result

- Il link del primo file appare all'interno dell'editor del primo allegato
- Il link del secondo file appare all'interno dell'editor del primo allegato subito dopo il link precedente

![2023_06_30_10_09_08_Articoli_Modifica_I I S _G _Spagna_F lli_Campani_Amministrazione](https://github.com/pcrt/joomla-italia-theme/assets/47560555/7de3bbb5-bb5b-4414-b6eb-e331eb0cb078)
![2023_06_30_10_11_27_Articoli_Modifica_I I S _G _Spagna_F lli_Campani_Amministrazione](https://github.com/pcrt/joomla-italia-theme/assets/47560555/9d87bf62-51fb-48c1-a65b-043b69ed5ac8)

**Comment by Knock-Out** [comment]
È un bug conosciuto di Joomla!.

**Comment by danilomariotti** [comment]
Perfetto, grazie!

**Comment by pcrt** [comment]
prova ad utilizzare acf (advanced custom field) di Tassos marinos. Io ho risolto così qui:
https://www.liceogalileilamezia.edu.it/istituto/organigramma.html
posso poi inviarti il layout alternativo per quel custom field

**Comment by danilomariotti** [comment]
Scaricato e installato ma che tipo di campo dovrei usare x l'allegato?

**Comment by pcrt** [comment]
considera che ti serve la versione pro. Crei un campo di tipo acfcaricamento file ed poi crei un campo di tipo subform e lo includi.
Questa la configurazione del campo allegato:
![Screenshot 2023-06-30 alle 16 56 35](https://github.com/pcrt/jo
![Screenshot 2023-06-30 alle 16 56 48](https://github.com/pcrt/joomla-italia-theme/assets/44270932/d6af7065-1ab4-4046-806d-ff7a2feecbe0)
omla-italia-theme/assets/44270932/95e24fdd-a5e6-4781-b48e-7c14ba573402)

**Comment by danilomariotti** [comment]
Ah... ecco perché. Allora credo che per ora mi tengo il Bug. Sto pensando di utilizzare una estensione dedicata alla gestione degli allegati anche se così mi perderei la formattazione a "card" del template, tipo Jlex Attachments.

**Comment by danilomariotti** [comment]
Scusa l'O.T. ma non riesco a risulvere il problema #16 , ho controllato mille volte!!!
