### ISSUE TITLE
Icone social non visualizzate con sito installato in una sottocartella

### ISSUE THREAD

**Issue by danilomariotti** [pcrt/joomla-italia-theme#4]
Ho installato il sito in una sottocartella ed ho notato che, al contrario di altri elementi, l’href delle icone social punta a /templates/joomla-italia-theme/… invece di /cartella/templates/joomla-italia-theme/… Nella configurazione del template ho indicato semplicemente il nome dell’cona, es: it-facebook.

**Comment by danilomariotti** [comment]
Stesso problema per l'icona lato destro in top-bar. Il problema potrebbe riguardare anche altre parti del template.

**Comment by danilomariotti** [comment]
Il problema della sottocartella si ripete anche nei link del logo in alto a sinistra e relative descrizioni che dovrebbero portare alla home all'interno della sottocartella

**Comment by danilomariotti** [comment]
L'icona Cerca soffre dello stesso problema

**Comment by MarcelloRocca** [comment]
Ho riscontato lo stesso problema.

**Comment by danilomariotti** [comment]
Io ho installato il sito nella sottocartella "sitoj4", come si può vedere nell'URL riportato nelle immagini allegate. Ispezionando le icone si vede che l'href punta a /templates e quindi riparte dalla radice e non dalla sottocartella. Questo problema è diffuso in diverse parti del sito, non solamente le icone o immagini, come si evince, ad esempio, dall'href del logo che punta a "/".
Con l'occasione vorrei far notare anche che, al restringersi della finestra, fino alla visualizzazione su cellulare soprattutto, la barra bianca che contiene il logo e le descrizioni non è più sufficiente in altezza e non riesce a contenere tutti glie elementi.

![2023_06_06_11_18_27_Home](https://github.com/pcrt/joomla-italia-theme/assets/47560555/cf094408-035d-43e9-9bc8-2625c633b79d)
![2023_06_06_11_19_08_Home](https://github.com/pcrt/joomla-italia-theme/assets/47560555/68e57552-c0c2-4f0a-9fb3-53c4dd06b0c0)
![2023_06_06_11_20_34_Home](https://github.com/pcrt/joomla-italia-theme/assets/47560555/94ad381c-bda7-4dad-9dc4-aaa550c62129)

**Comment by Knock-Out** [comment]
Adesso è chiaro, grazie. Prova a disattivare, dalle impostazioni SEO, riscrivi url.

**Comment by danilomariotti** [comment]
Al momento posso indicarti questi problemi:

- icona area riservata barra in alto
- icona cerca barra in alto
- icone social barra in alto
- link alla home del sito del logo in alto a sinistra
- icone luoghi nei box dell'elenco I luoghi
- icone documenti nei box dell'elenco Le carte della scuola
- icone strutture nei box dell'elenco Organizzazione

**Comment by danilomariotti** [comment]
Aggiungo:

- icona bandiera nei box delle strutture in "La scuola"

**Comment by danilomariotti** [comment]
Aggiungo ancora:
immagine in basso a sinistra su "Didattica" -> "Offerta formativa"

**Comment by pcrt** [comment]
> Al momento posso indicarti questi problemi:
> 
> * icona area riservata barra in alto
> * icona cerca barra in alto
> * icone social barra in alto
> * link alla home del sito del logo in alto a sinistra
> * icone luoghi nei box dell'elenco I luoghi
> * icone documenti nei box dell'elenco Le carte della scuola
> * icone strutture nei box dell'elenco Organizzazione
> 
> Questo è l'indirizzo del mio sito di test, molto work-in-progress!!!
> 
> https://www.tecnicoprofessionalespoleto.edu.it/sitoj4/

Puoi modificare questo commento aggiungendo qui senza aprirne di nuovi.
Grazie
