### ISSUE TITLE
Blog per le categorie della sezione organizzazione della scuola > Vedi tutti

### ISSUE THREAD

**Issue by Knock-Out** [pcrt/joomla-italia-theme#43]
###  Steps to reproduce the issue

1. Crea una Categoria denominata Organizzazione
2. Crea una sotto categoria di Organizzazione denominata  es. Segreteria
3. Crea un articolo denominato Segreteria, seleziona la sotto categoria di Organizzazione denominata Segreteria
________________

1. Crea una Voce di menu denominata Organizzazione di tipo "Blog per le categorie della sezione organizzazione della scuola"
2. Scegli una categoria * Organizzazione
________________

1. Crea una sotto Voce di menu di Organizzazione denominata Segreteria di tipo "Pagina Scuola"
2. Scegli una categoria * Segreteria
________________

### Actual result

![Organizzazione](https://github.com/pcrt/joomla-italia-theme/assets/24791536/4a83be19-7c1e-4935-ad5d-1de687824442)

### Expected result

ll collegamento 'Vedi tutti' non dovrebbe essere presente, perché rimanda alla pagina della sotto Categoria di Organizzazione. Ho provato a disattivare alcune opzioni della voce di menu di tipo 'Blog per le categorie della sezione organizzazione della scuola', ma nessuna opzione disattiva quel collegamento.

![Joomla Italia Theme - Segreteria](https://github.com/pcrt/joomla-italia-theme/assets/24791536/8402491f-8b51-4c17-a45a-435541ad8243)

In allegato immagine modello Wordpress.

![Strutture – Istituto comprensivo Statale](https://github.com/pcrt/joomla-italia-theme/assets/24791536/d7213286-ff26-4183-8787-23f1242aa670)

**Comment by pcrt** [comment]
la voce vedi tutti funziona se si crea prima una sottovoce di menu "nascosta" figlia della voce "Organizzazione"
