### ISSUE TITLE
Impossibile caricare/selezionare loghi template in formato svg

### ISSUE THREAD

**Issue by danilomariotti** [pcrt/joomla-italia-theme#5]
Nella personalizzazione del template non è possibile caricare e/o selezionare  i loghi in formato svg.
Il sito demo invece riporta i due loghi della repubblica (bianco e nero) in formato svg.

**Comment by mariantanase** [comment]
@danilomariotti ,
Questa issue non è un problema del template.
Devi configurare joomla aggiungendo svg tra le estensioni abilitate. Ci sono 3 posti da modificare.
Questa guida di Brian Teeman e perfetta: https://www.youtube.com/watch?v=U7hHYpuNqsg

**Comment by pcrt** [comment]
Si tratta di una configurazione di Joomla. Non sono necessarie modifiche.
