### ISSUE TITLE
La pubblicazione del Form di login provoca un malfunzionamento di owl-carousel

### ISSUE THREAD

**Issue by danilomariotti** [pcrt/joomla-italia-theme#50]
Steps to reproduce

- Pubblicare il form di login in una qualsia posizione, es below

Expected results

- Il form appare ed il banner funziona regolarmente

Actual results

- Il form appare e il banner non funziona più, le slide appaiono una sotto l'altra

- L'ispezione del codice riporta un errore su owl-carousel

![2023_07_05_22_54_18_Home](https://github.com/pcrt/joomla-italia-theme/assets/47560555/be24744b-2035-413f-a49a-4a3a6a2d3821)
![2023_07_05_22_55_32_Home](https://github.com/pcrt/joomla-italia-theme/assets/47560555/3705a658-605e-4fc1-9435-b10737503752)

**Comment by pcrt** [comment]
il modulo login non è ancora stato implementato nel template.

**Comment by danilomariotti** [comment]
Credo di aver capito dove sta il problema e non dovrebbe dipendere nello specifico dal modulo di login:
![2023_07_06_17_49_53_Home](https://github.com/pcrt/joomla-italia-theme/assets/47560555/4e4b00ea-ac88-40f2-87ee-dd25d4ffbf4c)
In alcuni casi (non sempre, ad esempio non dopo avere effettuato il login) c'è un doppio riferimento a jquery che, tra l'altro, viene dopo il riferimento a owl-carousel che invece dovrebbe venire per ultimo, se non sbaglio.
Togliendo il secondo riferimento, ad esempio rinominando il .js di jquery nel template, funziona tutto perfettamente.
